<?php

namespace App\Http\Services;

class InternalTestLayout
{
    public const HEADERS = [
        'Prov',
        'DIVISION',
        'MES',
        'SKU',
        '# CODIGO',
        'CODIGO',
        'FECHA',
        'HORA',
        'FECHA TERMINO PRUEBAS',
        'FECHA DE ENVIO DE REPORTE',
        'ANALISTA',
        'DEPARTAMENTO',
        'CONFECCIONISTA',
        'ESTILO',
        'DESCRIPCION',
        'IMP ETIQ',
        'SOLICITANTE',
        'COMENTARIOS',
        'Estatus Lab CCP',
        'Clasificacion Rechazo',
        'Motivo Rech Lab',
        'Motivo Rech Lab2',
        'Fecha Comité',
        'Estatus Comité',
        'SEGUIMIENTO COMITÉ CALIDAD',
        'Liberacion Compras',
        'FECHA LIB COMPRAS',
        'Status Final',
        '3 C DIMEN',
        '2 TORSION',
        '5 APARIENCIA',
        '1 PESO',
        '9 FROTE',
        '4 PILLING',
        '6 RASGADO',
        '7 TRACCION',
        '8 LAVADO ACELERADO',
        '10 DENSIDAD',
        '11 MICROSCOPIO',
        'TIPO DE LAVADO',
        'TEMPERATURA DE LAVADO',
        'TIPO DE SECADO',
        'PLANCHADO',
        'OC',
        'No. Reporte',
        'Reingreso',
        'Estatus de Calidad',
        'Estatus de Compras',
        'Motivo de Rechazo',
        'PROV TELA',
        'COMPOSICION',
        'RECIBO CEDIS',
        'PRIORIDAD',
        'FASE',
        'Peso (g/m2)',
    ];
}
