server {
    listen 80;

    root /var/www/html;
    index index.php index.html;

    server_name _;

location / {
    try_files $uri /index.php?$query_string;
}
    }

    # 🔥 IMPORTANTE
    location ~ \.php$ {
        try_files $uri =404;
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
