apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-github
  labels:
    app: nginx-github
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-github
  template:
    metadata:
      labels:
        app: nginx-github
    spec:
      containers:
      - name: nginx
        image: ghcr.io/jcvillagran89/nginx-k8s-demo:latest
        ports:
        - containerPort: 80
        env:
        - name: LD_LIBRARY_PATH
          value: /opt/oracle/instantclient
