name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        docker build -t nginx-github:v1 .

    - name: Import image to k3s
      run: |
        docker save nginx-github:v1 -o nginx.tar
        sudo ctr -n k8s.io images import nginx.tar
    - name: Restart deployment
      run: |
        kubectl rollout restart deployment nginx-github
